version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_springboot
    environment:
      POSTGRES_DB: comicDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - springboot-network

  redis:
    image: 'redis:7.4.2'
    container_name: 'redis'
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

  redis-commander:
    container_name: 'redis-commander'
    image: 'rediscommander/redis-commander:latest'
    restart: 'always'
    depends_on:
      - 'redis'
    ports:
      - '8081:8081'
    environment:
      - 'REDIS_HOSTS=local:redis:6379'

volumes:
  postgres_data:

networks:
  springboot-network:
