version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_springboot
    environment:
      POSTGRES_DB: comicDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - springboot-network

volumes:
  postgres_data:

networks:
  springboot-network:
